### ISSUE TITLE
Change /javascripts directory to /js?

### ISSUE THREAD

**Issue by tohuw** [octopress/littlefoot#2]
When I include the assets, it creates a /javascripts directory. I'd rather it put that file in /js. How do I change that behavior?

**Comment by tohuw** [comment]
On further investigation, the `<head>` element contains links to invalid locations:
    <link href="/littlefoot/stylesheets/littlefoot.css" media="all" rel="stylesheet" type="text/css">
    <script src="/littlefoot/javascripts/littlefoot.js"></script>

It also seems this plugin calls or uses the same code as octopress-asset-pipeline? I experimented with removing this gem and calls to it, and fiddling about with my config. The issues remain. What am I missing?

**Comment by tohuw** [comment]
Here's the relevant section of my config:

```
asset_pipeline:
  stylesheets_dir: /css
  combine_css: false
  compress_css: true
  order_css: []
  javascripts_dir: /js
  combine_js: false
  compress_js: true
  order_js: []
```

**Comment by tohuw** [comment]
Okay, I sorted things out, but it required using `stylesheets` and `javascripts`, when I'd rather use `css` and `js`. Now that they're all in there, everything combines as I expect.

How can I configure octopress ink and asset-pipeline to properly use these directories?

For posterity, my updated config section:

```
asset_pipeline:
  stylesheets_dir: 'stylesheets'
  combine_css: true
  compress_css: true
  order_css: []
  javascripts_dir: 'javascripts'
  combine_js: true
  compress_js: true
  order_js: []
```
